name: 'Setup Rust environment'
description: 'Setup a Rust environment and add it to the PATH, additionally providing custom target support'
author: 'Raphaël Thériault'
inputs:
  rust-channel:
    description: 'Rust channel (version) to use (defaults to stable)'
    default: 'stable'
  rust-host:
    description: 'Rust host to use (defaults to current platform)'
    default: ''
  rust-target:
    description: 'Rust target to compile for (defaults to current host)'
    default: ''
runs:
  using: 'node12'
  main: 'lib/main.js'
