name: 'Setup Rust environment'
description: 'Setup a Rust environment and add it to the PATH, additionally providing custom target support'
author: 'Raphaël Thériault'
inputs:
  rust-channel:
    description: 'Rust channel (version) to use'
    default: 'stable'
runs:
  using: 'node12'
  main: 'lib/main.js'
