name: "Checks"
on: [pull_request, push]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: "Install dependencies"
      run: yarn
    - name: "Build"
      run: yarn build
    - name: "Test"
      run: yarn test
    - name: "Lint"
      run: yarn lint
    - name: "Check for uncommitted changes"
      # Ensure no changes, but ignore node_modules dir since dev/fresh ci deps installed.
      run: |
        git diff --exit-code --stat -- . ':!node_modules' \
        || (echo "##[error] found changed files after build. please 'npm run build && npm run format'" \
                 "and check in all changes" \
            && exit 1)
